// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ00i51yeiAIDP0PoMNzZzvA4VMjojrc4',
    appId: '1:669182239244:android:d082b80f6e19c152a44429',
    messagingSenderId: '669182239244',
    projectId: 'gimie-launch',
    storageBucket: 'gimie-launch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxn5Y9I5gmktlvG1hIPlkq_4A2DXdTs8M',
    appId: '1:669182239244:ios:dc1504841eeb2015a44429',
    messagingSenderId: '669182239244',
    projectId: 'gimie-launch',
    storageBucket: 'gimie-launch.firebasestorage.app',
    iosClientId: '669182239244-dlb360380jnlhihqljg2j3ip614dpdrk.apps.googleusercontent.com',
    iosBundleId: 'com.gimie.gimie',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADHRnBcd5A8oYkGMz44JAA51wKtcyEwnA',
    appId: '1:669182239244:web:d03101f5719e424aa44429',
    messagingSenderId: '669182239244',
    projectId: 'gimie-launch',
    authDomain: 'gimie-launch.firebaseapp.com',
    storageBucket: 'gimie-launch.firebasestorage.app',
    measurementId: 'G-63P8RYYLRV',
  );

}